# Generated by Django 6.0.6 on 2026-06-23 16:24

import django.db.models.deletion
import placeme.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeme', '0002_feedback_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('headline', models.CharField(blank=True, default='', help_text='e.g. "BTech Full Stack Developer"', max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=placeme.models.profile_pic_path)),
                ('resume', models.FileField(blank=True, null=True, upload_to=placeme.models.resume_path)),
                ('skills', models.TextField(blank=True, default='', help_text='Comma-separated list of skills')),
                ('degree', models.CharField(blank=True, default='', max_length=255)),
                ('institution', models.CharField(blank=True, default='', max_length=255)),
                ('graduation_date', models.CharField(blank=True, default='', help_text='e.g. May 2025', max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('1-3', '1–3 Years'), ('3-5', '3–5 Years'), ('senior', 'Senior (5+ Years)')], default='', max_length=20)),
                ('projects', models.TextField(blank=True, default='', help_text='Brief list of key projects or internships')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('location_city', models.CharField(blank=True, default='', max_length=100)),
                ('location_country', models.CharField(blank=True, default='', max_length=100)),
                ('linkedin', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('portfolio', models.URLField(blank=True, default='')),
                ('target_roles', models.CharField(blank=True, default='', help_text='e.g. Software Engineering, Data Analyst', max_length=255)),
                ('interview_type', models.CharField(blank=True, choices=[('technical', 'Technical'), ('behavioral', 'Behavioural'), ('mix', 'Mix of Both')], default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
