# Generated by Django 6.0.6 on 2026-06-25 15:52

import django.db.models.deletion
import placeme.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeme', '0004_remove_userprofile_degree_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_roles', models.CharField(blank=True, default='', max_length=255)),
                ('extra_skills', models.CharField(blank=True, default='', max_length=500)),
                ('job_description', models.TextField(blank=True, default='')),
                ('interview_type', models.CharField(blank=True, choices=[('technical', 'Technical'), ('behavioral', 'Behavioural'), ('mix', 'Mix of Both')], default='', max_length=20)),
                ('tone', models.CharField(blank=True, choices=[('friendly', 'Friendly'), ('standard', 'Standard'), ('strict', 'Strict')], default='standard', max_length=20)),
                ('depth', models.CharField(blank=True, choices=[('quickfire', 'Quick-Fire'), ('deepdive', 'Deep-Dive Scenarios')], default='quickfire', max_length=20)),
                ('num_questions', models.IntegerField(default=10)),
                ('resume', models.FileField(blank=True, null=True, upload_to=placeme.models.interview_resume_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_preferences',
            },
        ),
    ]
