# Generated by Django 6.0.6 on 2026-06-26 15:57

import django.db.models.deletion
import placeme.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeme', '0005_interviewpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_roles', models.CharField(blank=True, default='', max_length=255)),
                ('additional_skills', models.CharField(blank=True, default='', max_length=500)),
                ('job_description', models.TextField(blank=True, default='')),
                ('interview_preference', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioural'), ('mix', 'Mix of Both')], default='mix', max_length=20)),
                ('interviewer_tone', models.CharField(choices=[('friendly', 'Friendly'), ('standard', 'Standard'), ('strict', 'Strict')], default='standard', max_length=20)),
                ('question_depth', models.CharField(choices=[('quickfire', 'Quick-Fire'), ('deepdive', 'Deep-Dive Scenarios')], default='quickfire', max_length=20)),
                ('number_of_questions', models.IntegerField(choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20')], default=10)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to=placeme.models.session_resume_path)),
                ('chat_history', models.JSONField(default=list)),
                ('current_question_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
