# Generated by Django 6.0.6 on 2026-07-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeme', '0006_interviewsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='feedback',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
